// Access JWT verification (SPEC sections 10.2 and 10.3). Production verifies
// against the team's remote JWKS; dev and test use the same function with a
// local JWKS generated by `npm run dev:keys` (or by vitest).

import { createLocalJWKSet, createRemoteJWKSet, jwtVerify, type JWTPayload, type JWTVerifyGetKey } from "jose";
import type { Config } from "../config.ts";

export const ACCESS_HEADER = "Cf-Access-Jwt-Assertion";
export const ACCESS_COOKIE = "CF_Authorization";

const remoteSets = new Map<string, JWTVerifyGetKey>();
const localSets = new WeakMap<object, JWTVerifyGetKey>();

/** JWKS for this config, memoized per isolate (jose handles kid rotation and refetch). */
export function jwksFor(config: Config): JWTVerifyGetKey {
  if (config.authMode === "dev") {
    const jwks = config.accessDevJwks;
    if (!jwks) throw new Error("dev auth without ACCESS_DEV_JWKS");
    let set = localSets.get(jwks);
    if (!set) {
      set = createLocalJWKSet(jwks as unknown as Parameters<typeof createLocalJWKSet>[0]);
      localSets.set(jwks, set);
    }
    return set;
  }
  const url = `${config.accessTeamDomain}/cdn-cgi/access/certs`;
  let set = remoteSets.get(url);
  if (!set) {
    set = createRemoteJWKSet(new URL(url));
    remoteSets.set(url, set);
  }
  return set;
}

export async function verifyAccessJwt(token: string, config: Config): Promise<JWTPayload> {
  const { payload } = await jwtVerify(token, jwksFor(config), {
    issuer: config.accessTeamDomain,
    audience: config.accessAud,
    algorithms: ["RS256"],
    clockTolerance: 30,
  });
  return payload;
}

/**
 * Token source: the `Cf-Access-Jwt-Assertion` header only in access mode
 * (Cloudflare documents that the cookie is not guaranteed). Dev mode falls back
 * to the `CF_Authorization` cookie so the browser and WebSockets work without Access.
 */
export function extractAccessToken(request: Request, config: Config): string | null {
  const header = request.headers.get(ACCESS_HEADER);
  if (header && header.trim()) return header.trim();
  if (config.authMode !== "dev") return null;
  return readCookie(request.headers.get("Cookie"), ACCESS_COOKIE);
}

export function readCookie(cookieHeader: string | null, name: string): string | null {
  if (!cookieHeader) return null;
  for (const part of cookieHeader.split(";")) {
    const index = part.indexOf("=");
    if (index < 0) continue;
    if (part.slice(0, index).trim() === name) {
      const value = part.slice(index + 1).trim();
      return value || null;
    }
  }
  return null;
}

const LOOPBACK_HOSTS = new Set(["localhost", "127.0.0.1", "[::1]"]);

/** True only for loopback hostnames; the dev servers bind loopback only (SPEC section 10.3). */
export function isLoopbackRequest(request: Request): boolean {
  return LOOPBACK_HOSTS.has(new URL(request.url).hostname);
}
