-- Generated by `npm run synth` from the seeded dataset. Do not edit by hand.

INSERT INTO role_bindings (principal, role, display_name, created_at, updated_at, updated_by) VALUES ('viewer.ana@agentboard.test', 'viewer', 'Ana Viewer', '2026-09-01T00:00:00.000Z', '2026-09-01T00:00:00.000Z', 'seed');
INSERT INTO role_bindings (principal, role, display_name, created_at, updated_at, updated_by) VALUES ('viewer.ben@agentboard.test', 'viewer', 'Ben Viewer', '2026-09-01T00:00:00.000Z', '2026-09-01T00:00:00.000Z', 'seed');
INSERT INTO role_bindings (principal, role, display_name, created_at, updated_at, updated_by) VALUES ('ops.lead@agentboard.test', 'operator', 'Ops Lead', '2026-09-01T00:00:00.000Z', '2026-09-01T00:00:00.000Z', 'seed');
INSERT INTO role_bindings (principal, role, display_name, created_at, updated_at, updated_by) VALUES ('ops.kim@agentboard.test', 'operator', 'Kim Operator', '2026-09-01T00:00:00.000Z', '2026-09-01T00:00:00.000Z', 'seed');
INSERT INTO role_bindings (principal, role, display_name, created_at, updated_at, updated_by) VALUES ('ops.raj@agentboard.test', 'operator', 'Raj Operator', '2026-09-01T00:00:00.000Z', '2026-09-01T00:00:00.000Z', 'seed');
INSERT INTO role_bindings (principal, role, display_name, created_at, updated_at, updated_by) VALUES ('approver.lee@agentboard.test', 'approver', 'Lee Approver', '2026-09-01T00:00:00.000Z', '2026-09-01T00:00:00.000Z', 'seed');
INSERT INTO role_bindings (principal, role, display_name, created_at, updated_at, updated_by) VALUES ('approver.mia@agentboard.test', 'approver', 'Mia Approver', '2026-09-01T00:00:00.000Z', '2026-09-01T00:00:00.000Z', 'seed');
INSERT INTO role_bindings (principal, role, display_name, created_at, updated_at, updated_by) VALUES ('admin@agentboard.test', 'admin', 'Admin', '2026-09-01T00:00:00.000Z', '2026-09-01T00:00:00.000Z', 'seed');
INSERT INTO role_bindings (principal, role, display_name, created_at, updated_at, updated_by) VALUES ('svc:agentboard-eval', 'operator', 'Eval service token', '2026-09-01T00:00:00.000Z', '2026-09-01T00:00:00.000Z', 'seed');
INSERT INTO agent_controls (role, disabled, reason, updated_by, updated_at) VALUES ('planner', 0, NULL, 'seed', '2026-09-01T00:00:00.000Z');
INSERT INTO agent_controls (role, disabled, reason, updated_by, updated_at) VALUES ('executor', 0, NULL, 'seed', '2026-09-01T00:00:00.000Z');
INSERT INTO agent_controls (role, disabled, reason, updated_by, updated_at) VALUES ('verifier', 0, NULL, 'seed', '2026-09-01T00:00:00.000Z');
